### ISSUE TITLE
privacy concerns

### ISSUE THREAD

**Issue by bingoxo** [meganz/iOS#66]
why does the app collect this much data ?

![rasKDg3lCM](https://user-images.githubusercontent.com/49401307/151332010-4460053f-40e9-46c1-bba4-e42997d03459.png)

**Comment by sakethv-mega** [comment]
Hello, you can find more explanation about what and how we use this data for here - https://help.mega.io/installs-apps/mobile/ios-app-permissions

Thank you.

**Comment by bingoxo** [comment]
what about purchases ?

contact info/location/contacts seem to be related to mega chat which i (and i'm sure i'm not alone) don't use so i prefer that they aren't collected

**Comment by Barraguesh** [comment]
@bingoxo just because the app may use it doesn't mean it actively uses it. For example, the location permission it's usually for uploading in the background (common in other apps), so if you don't use it or enable it, the app won't be using it.

These have to be disclosed at its maximum extent, but doesn't mean that in your case, all are used. For example, if you don't use the chat option, the app has not asked you for access to contacts and the permission is not enabled as you're not using the feature that needs it.

**Comment by flofeil** [comment]
I think Barraguesh explained your issue perfectly. Can you close the issue?

**Comment by bingoxo** [comment]
> @bingoxo just because the app may use it doesn't mean it actively uses it. For example, the location permission it's usually for uploading in the background (common in other apps), so if you don't use it or enable it, the app won't be using it.
> 
> These have to be disclosed at its maximum extent, but doesn't mean that in your case, all are used. For example, if you don't use the chat option, the app has not asked you for access to contacts and the permission is not enabled as you're not using the feature that needs it.

i don't remember correctly but i think many of the permissions were activated by default when installing the app , can you make them optional after please ?

and you haven't answered why is the app collecting purchases data ?

**Comment by flofeil** [comment]
As you may be aware, iOS verifies your permission the first time you open the app. Furthermore the app will function without the permission's. 

You can purchase more storage space in app.
